server:
  port: 8081

spring:
  application:
    name: rabbit-mq-provider
  rabbitmq:
    host: localhost
    port: 5672
    username: david
    password: 123456
    publisher-confirms: true
    virtual-host: /